# Generated by Django 5.0.3 on 2024-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('peluqueria', 'Peluquería'), ('cirugia', 'Cirugía'), ('atencion_veterinaria', 'Atención Veterinaria')], max_length=50)),
                ('tipo_turno', models.CharField(choices=[('bano', 'Baño'), ('corte_o_bano', 'Corte o Baño'), ('castracion', 'Castración'), ('otros', 'Otros'), ('vacunacion', 'Vacunación'), ('atencion', 'Atención')], max_length=50)),
                ('fecha', models.DateField()),
                ('horario_disponible', models.TimeField()),
            ],
        ),
    ]
